IF OBJECT_ID('HoaDonNhap','U') IS NOT NULL
BEGIN
	ALTER TABLE HoaDonNhap DROP CONSTRAINT FK_HoaDonNhap_Thuoc;
	ALTER TABLE HoaDonNhap DROP CONSTRAINT FK_HoaDonNhap_NhanVien;
	DROP TABLE HoaDonNhap;
END;

IF OBJECT_ID('HoaDonXuat','U') IS NOT NULL
BEGIN
	ALTER TABLE HoaDonXuat DROP CONSTRAINT FK_HoaDonXuat_BenhNhan;
	ALTER TABLE HoaDonXuat DROP CONSTRAINT FK_HoaDonXuat_NhanVien;
	DROP TABLE HoaDonXuat;
END;

IF OBJECT_ID('Thuoc','U') IS NOT NULL
BEGIN
	ALTER TABLE Thuoc DROP CONSTRAINT FK_Thuoc_NhomThuoc;
	ALTER TABLE Thuoc DROP CONSTRAINT FK_Thuoc_NSX;
	DROP TABLE Thuoc;
END;

IF OBJECT_ID('NhanVien','U') IS NOT NULL
BEGIN
	ALTER TABLE NhanVien DROP CONSTRAINT FK_NhanVien_PhongBan;
	DROP TABLE NhanVien;
END;

IF OBJECT_ID('NhomThuoc','U') IS NOT NULL
BEGIN
	DROP TABLE NhomThuoc;
END;

IF OBJECT_ID('NhaSanXuat','U') IS NOT NULL
BEGIN
	DROP TABLE NhaSanXuat;
END;

IF OBJECT_ID('BenhNhan','U') IS NOT NULL
BEGIN
	DROP TABLE BenhNhan;
END;

IF OBJECT_ID('PhongBan','U') IS NOT NULL
BEGIN
	DROP TABLE PhongBan;
END;